
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.20 (64bit) on [Tue May 24 20:25:01 2022] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 13 May 2022 14:00:48
os: Linux-3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021
nodename: hadoop03
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /usr/local/workspace/IntelligentSystem
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /usr/local/workspace/IntelligentSystem/
your processes number limit is 15066
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8997 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0xc7b100
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xc7b100 pid: 30938 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30938)
spawned uWSGI worker 1 (pid: 30961, cores: 2)
spawned uWSGI worker 2 (pid: 30963, cores: 2)
spawned uWSGI worker 3 (pid: 30965, cores: 2)
spawned uWSGI worker 4 (pid: 30967, cores: 2)
Tue May 24 20:26:54 2022 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue May 24 20:26:54 2022 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue May 24 20:26:54 2022 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue May 24 20:26:54 2022 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue May 24 20:26:54 2022 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue May 24 20:26:54 2022 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue May 24 20:26:54 2022 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue May 24 20:26:54 2022 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.20 (64bit) on [Tue May 24 20:27:43 2022] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 13 May 2022 14:00:48
os: Linux-3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021
nodename: hadoop03
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /usr/local/workspace/IntelligentSystem
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /usr/local/workspace/IntelligentSystem/
your processes number limit is 15066
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8997 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0xfdd100
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xfdd100 pid: 31391 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 31391)
spawned uWSGI worker 1 (pid: 31396, cores: 2)
spawned uWSGI worker 2 (pid: 31398, cores: 2)
spawned uWSGI worker 3 (pid: 31399, cores: 2)
spawned uWSGI worker 4 (pid: 31400, cores: 2)
*** Starting uWSGI 2.0.20 (64bit) on [Tue May 24 20:36:43 2022] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 13 May 2022 14:00:48
os: Linux-3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021
nodename: hadoop03
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /usr/local/workspace/IntelligentSystem
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /usr/local/workspace/IntelligentSystem/
your processes number limit is 15066
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8997).
bind(): Address already in use [core/socket.c line 769]
